Fix NameError: global name 'Logs' is not defined
2018-09-23 16:57:14,316 (3cf50) :  CRITICAL (core:574) - Exception in the update function of agent named 'Lambda', called with guid 'com.plexapp.agents.imdb://tt0800080?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-21ab172de\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "D:\Plex\Plex Media Server\Plug-ins\Lambda.bundle\Contents\Code\__init__.py", line 680, in update
    def update (self, metadata, media, lang, force ):  Update(metadata, media, lang, force,  'movie')
  File "D:\Plex\Plex Media Server\Plug-ins\Lambda.bundle\Contents\Code\__init__.py", line 657, in Update
    Logs.Info('[!] collection "{}" renamed in of the following: "{}". Please remove old collection tag and add new one'.format(collection, collection_list.keys()))
NameError: global name 'Logs' is not defined